apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logcheckers.oci.operator
spec:
  group: oci.operator
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName: 
                  type: string
                namespace:
                  type: string
                searchString:
                  type: string
            status:
              type: object
              properties:
                found:
                  type: boolean
                lastChecked:
                  type: string
                matchingLines:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: logcheckers
    singular: logchecker
    kind: LogChecker
    shortNames:
      - lc

