apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logchecker-operator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch","delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "create","watch"]
  - apiGroups: ["oci.operator"]
    resources: ["logcheckers"]
    verbs: ["get", "list", "watch", "create", "update", "delete","patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

