apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logchecker-operator-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["oci.operator"]
    resources: ["logcheckers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

