apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logchecker-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: logchecker-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: logchecker-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

